name: riverpod_builder
description: the package to use Riverpod's Provider like the ListView and PageView widgets.We believe that Flutter development can handle it easily.
version: 0.2.0
homepage: 'https://github.com/den0206/riverpod_builder'
platforms:
  android:
  ios:

environment:
  sdk: '>=2.18.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: '>=2.1.3 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# flutter pub publish --dry-run
flutter:
